config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'

	post 'rooms', to: 'welcome#create_rooms', as: 'create_room'
	match 'rooms/:room_name', to: 'welcome#rooms', as: 'rooms', via: [:get, :post]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout "main"

	def create_rooms
		cookies.signed[:nick_name] = params[:nick_name]
		cookies.signed[:room_name] = params[:room_name]
		redirect_to rooms_path(room_name: params[:room_name].parameterize)
	end

	def rooms
		render 'rooms'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
	<style>
		.centered {
			float: none;
			margin: 0 auto;
		}

	</style>
</head>
<body>
	<%= yield %>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue@2.5.11/dist/vue.js"></script>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/welcome/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>Rails & Vue Chat</h1>
		</div>
	</div>
	<hr>
	<%= form_tag create_room_path, method: :post, autocomplete: 'off' do |f| %>
		<div class="row text-center">
			<div class="col-md-5 centered">
				<label for="room_name">Oda İsmini Giriniz:</label>
				<input type="text" required name="room_name" id="room_name" placeholder="Oda adını giriniz." class="form-control text-center" style="height: 50px; font-size: 25px; border-radius: 5px">
			</div>

			<div class="row text-center" style="margin-top: 20px">
				<div class="col-md-5 centered">
					<label for="nickname">Takma Adınızı Giriniz.</label>
					<input type="text" required name="nick_name" placeholder="Takma Adınız." class="form-control text-center" style="height: 50px; font-size: 25px; border-radius: 5px">
				</div>
			</div>

			<div class="row" style="margin-top: 20px;">
				<div class="col-md-5 centered">
					<button class="btn btn-lg btn-success" style="width: 200px"><b>Oluştur</b></button>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/welcome/rooms.html.erb
<div class="app">
	<div class="container-fluid">
		<div class="col-md-10">
			<ul class="list-group" style="list-style: none; width: %100;">
				<template v-for="message in messages">
					<li class="list-group-item">{{ message.user }} >> {{ message.data }}</li>
				</template>
			</ul>
		</div>
		
		<div class="col-md-2">
			<h4 class="text-center">Online Users</h4>
			<hr>
			<ul style="font-size: 19px; list-style: none;">
				<template v-for="list in online_list">
					<li>{{ list }}</li>
				</template>
			</ul>
		</div>
	</div>

	<div class="container-fluid">
		<form v-on:submit.prevent="send_message">
			<div class="navbar navbar-fixed-bottom">
				<div class="container-fluid">
					<div class="input-group">
							<input type="text" v-model="message" style="height: 40px; font-size: 20px" placeholder="Message your write in here" class="form-control">
							<div class="input-group-btn">
								<button class="btn" style="height: 40px;">
									Send
								</button>
							</div>
					</div>
				</div> 
			</div>
		</form>
	</div>
</div>

<script src="https://unpkg.com/vue@2.5.11/dist/vue.js"></script>
<%= javascript_include_tag 'action_cable_generator', 'data-turbolinks-track': 'reload' %>